# Generated by Django 4.0.5 on 2022-06-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0002_information'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
